version: '3.8'

services:
  seq:
    image: datalust/seq:latest
    container_name: aegisx-seq
    ports:
      - "5341:80"      # Seq UI
      - "5342:5342"    # Seq ingestion
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin123
      - SEQ_API_CANONICALURI=http://localhost:5341
    volumes:
      - seq_data:/data
    restart: unless-stopped
    networks:
      - aegisx-network

volumes:
  seq_data:

networks:
  aegisx-network:
    driver: bridge